### ISSUE TITLE
Shader is pink in mac os

### ISSUE THREAD

**Issue by ZhengzhongSun** [keijiro/GTeleporter#1]
I run this repo in Unity 2017.2.0f3 with mac, but it seems the shader is pink. Could you give me some advice? Thank you!

**Comment by keijiro** [comment]
It doesn't work on macOS by default because Metal doesn't support geometry shaders. You have to change the graphics API to OpenGL Core, I haven't tried it though.

**Comment by keijiro** [comment]
I'm closing the issue. Please feel free to reopen for further questions.
